import os
import unittest
from unittest.mock import MagicMock

from cumulus_api import CumulusApi


class TestMain(unittest.TestCase):
    def test_endpoint_functions(self):
        os.environ['PRIVATE_API_LAMBDA_ARN'] = 'FAKE_ARN'
        capi = CumulusApi()
        capi._CumulusApi__crud_records = MagicMock()
        fake_value = MagicMock()

        capi.apply_workflow_to_granule(granule_id=fake_value, workflow_name=fake_value)
        capi.associate_execution(data=fake_value)
        capi.bulk_delete(data=fake_value)
        capi.bulk_reingest(data=fake_value)
        capi.create_collection(data=fake_value)
        capi.create_execution(data=fake_value)
        capi.create_granule(data=fake_value)
        capi.create_provider(data=fake_value)
        capi.create_reconciliation_report()
        capi.create_rule(data=fake_value)
        capi.delete_collection(collection_name=fake_value, collection_version=fake_value)
        capi.delete_execution(execution_arn=fake_value)
        capi.delete_granule(granule_id=fake_value)
        capi.delete_pdr(pdr_name=fake_value)
        capi.delete_provider(provider_id=fake_value)
        capi.delete_reconciliation_report(report_name=fake_value)
        capi.delete_rule(rule_name=fake_value)
        capi.delete_token()
        capi.get_async_operation(operation_id=fake_value)
        capi.get_collection(collection_name=fake_value, collection_version=fake_value)
        capi.get_elasticsearch_index()
        capi.get_elasticsearch_indices_info()
        capi.get_elasticsearch_reindex_status()
        capi.get_execution(execution_arn=fake_value)
        capi.get_execution_status(execution_arn=fake_value)
        capi.get_granule(granule_id=fake_value)
        capi.get_granules_csv()
        capi.get_instance_metadata()
        capi.get_log(execution_name=fake_value)
        capi.get_pdr(pdr_name=fake_value)
        capi.get_provider(provider_id=fake_value)
        capi.get_reconciliation_report(report_name=fake_value)
        capi.get_rule(rule_name=fake_value)
        capi.get_schema(schema_type=fake_value)
        capi.get_stats_aggregate()
        capi.get_stats_summary()
        capi.get_token()
        capi.get_version()
        capi.get_workflow(workflow_name=fake_value)
        capi.granules_bulk_op(data=fake_value)
        capi.list_async_operations()
        capi.list_collections()
        capi.list_collections_with_active_granules()
        capi.list_executions()
        capi.list_granules()
        capi.list_logs()
        capi.list_pdrs()
        capi.list_providers()
        capi.list_reconciliation_reports()
        capi.list_rules()
        capi.list_workflows()
        capi.move_granule(granule_id=fake_value, regex=fake_value, bucket=fake_value, file_path=fake_value)
        capi.recover_cumulus_messages(bucket=fake_value, path=fake_value)
        capi.refresh_token()
        capi.reindex_elasticsearch()
        capi.reindex_elasticsearh_from_database()
        capi.reingest_granule(granule_id=fake_value, data=fake_value)
        capi.remove_granule_from_cmr(granule_id=fake_value)
        capi.replay_ingest_notification(data=fake_value)
        capi.run_migration_count()
        capi.run_rule(rule_name=fake_value)
        capi.search_executions_by_granules(data=fake_value)
        capi.search_workflows_by_granules(data=fake_value)
        capi.serve_dashboard_from_bucket(bucket=fake_value, key=fake_value)
        capi.update_collection(data=fake_value)
        capi.update_elasticsearch_index(data=fake_value)
        capi.update_execution(data=fake_value)
        capi.update_granule(data=fake_value)
        capi.update_provider(data=fake_value)
        capi.update_rule(data=fake_value)
